#PlayerAbilityLib configuration file
#
#If alwaysLogTamperWarnings is set to false, external update messages will be logged only once per game session
#Mon Sep 21 20:47:58 ICT 2026
alwaysLogTamperWarnings=true
